-- SQLite scripts to create and store the app's users
CREATE TABLE USERS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT, 
    USERNAME VARCHAR(64) NOT NULL,
    PASSWORD VARCHAR(64) NOT NULL,
    BAN_STATUS INT NOT NULL
);

INSERT INTO USERS (USERNAME, PASSWORD, BAN_STATUS)
VALUES ('root', 'root', 0);

INSERT INTO USERS (USERNAME, PASSWORD, BAN_STATUS)
VALUES ('admin', 'admin', 1);

INSERT INTO USERS (USERNAME, PASSWORD, BAN_STATUS)
VALUES ('ciprianos', 'lfacishard', 0);

INSERT INTO USERS (USERNAME, PASSWORD, BAN_STATUS)
VALUES ('ciprianos123', 'bdisharder', 0);

INSERT INTO USERS (USERNAME, PASSWORD, BAN_STATUS)
VALUES ('florinsalam', 'distractiamapamondului', 1);

