-- SQLite scripts to create and store the app's users
CREATE TABLE USERS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT, 
    USERNAME VARCHAR(64) NOT NULL,
    PASSWORD VARCHAR(64) NOT NULL,
    BAN_STATUS INT NOT NULL
);

INSERT INTO USERS (USERNAME, PASSWORD, BAN_STATUS)
VALUES ('root', '{xx}', 0); -- root e parola

INSERT INTO USERS (USERNAME, PASSWORD, BAN_STATUS)
VALUES ('admin', 'knwsx', 1); -- admin e parola

INSERT INTO USERS (USERNAME, PASSWORD, BAN_STATUS)
VALUES ('ciprianos', 'lfacishard', 1);

INSERT INTO USERS (USERNAME, PASSWORD, BAN_STATUS)
VALUES ('ciprianos123', 'bdisharder', 1);

INSERT INTO USERS (USERNAME, PASSWORD, BAN_STATUS)
VALUES ('florinsalam', 'distractiamapamondului', 1);

